//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nordwest.Wpf.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nordwest.Wpf.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No image.
        /// </summary>
        public static string MapControl_EmptyTileText {
            get {
                return ResourceManager.GetString("MapControl_EmptyTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string MapControl_ScaleRuler_ErrorText {
            get {
                return ResourceManager.GetString("MapControl_ScaleRuler_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на km.
        /// </summary>
        public static string MapControl_ScaleRuler_KmPostfix {
            get {
                return ResourceManager.GetString("MapControl_ScaleRuler_KmPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        public static string MapControl_ScaleRuler_MPostfix {
            get {
                return ResourceManager.GetString("MapControl_ScaleRuler_MPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на minZoom &gt; maxZoom.
        /// </summary>
        public static string MapPrefetcher_MinZoomGreaterThenMaxZoom_Exception {
            get {
                return ResourceManager.GetString("MapPrefetcher_MinZoomGreaterThenMaxZoom_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images BMP|*.BMP.
        /// </summary>
        public static string SaveToImageWindow_FileFormat {
            get {
                return ResourceManager.GetString("SaveToImageWindow_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid file name...
        /// </summary>
        public static string SaveToImageWindow_InvalidFilename_Message {
            get {
                return ResourceManager.GetString("SaveToImageWindow_InvalidFilename_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на km.
        /// </summary>
        public static string SaveToImageWindow_KilometersPostfix {
            get {
                return ResourceManager.GetString("SaveToImageWindow_KilometersPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        public static string SaveToImageWindow_MetersPostfix {
            get {
                return ResourceManager.GetString("SaveToImageWindow_MetersPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image processing....
        /// </summary>
        public static string SaveToImageWindow_PrepareImage_StatusText {
            get {
                return ResourceManager.GetString("SaveToImageWindow_PrepareImage_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SaveToImageWindow_SaveButton_Content {
            get {
                return ResourceManager.GetString("SaveToImageWindow_SaveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving... {0}%.
        /// </summary>
        public static string SaveToImageWindow_SaveingProgress_StatusText {
            get {
                return ResourceManager.GetString("SaveToImageWindow_SaveingProgress_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready!.
        /// </summary>
        public static string SaveToImageWindow_SavingDone_StatusText {
            get {
                return ResourceManager.GetString("SaveToImageWindow_SavingDone_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale: .
        /// </summary>
        public static string SaveToImageWindow_Scale_Text {
            get {
                return ResourceManager.GetString("SaveToImageWindow_Scale_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string SaveToImageWindow_ScaleRuler_ErrorText {
            get {
                return ResourceManager.GetString("SaveToImageWindow_ScaleRuler_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected site.
        /// </summary>
        public static string SaveToImageWindow_SelectedSiteCheckBox_Content {
            get {
                return ResourceManager.GetString("SaveToImageWindow_SelectedSiteCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Labels.
        /// </summary>
        public static string SaveToImageWindow_ShowLabelsCheckbox_Content {
            get {
                return ResourceManager.GetString("SaveToImageWindow_ShowLabelsCheckbox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        public static string SaveToImageWindow_Size_Text {
            get {
                return ResourceManager.GetString("SaveToImageWindow_Size_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save to image.
        /// </summary>
        public static string SaveToImageWindow_Title {
            get {
                return ResourceManager.GetString("SaveToImageWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom in.
        /// </summary>
        public static string ZoomControl_ZoomInTooltip {
            get {
                return ResourceManager.GetString("ZoomControl_ZoomInTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom out.
        /// </summary>
        public static string ZoomControl_ZoomOutTooltip {
            get {
                return ResourceManager.GetString("ZoomControl_ZoomOutTooltip", resourceCulture);
            }
        }
    }
}
